---
- name: ThousandEyes Webhook
  hosts: all
  sources:
   - ansible.eda.webhook:
       host: 0.0.0.0
       port: 10080

  rules:
    - name: Renew TLS Certificate
      condition: event.payload.alert.rule.expression is match("Certificate expires within", ignorecase=true) and event.payload.type == "2"
      action:
        run_playbook:
          name: ./renew_cert_playbook.yml
          post_events: true

    - name: Renew playbook success
      condition: event.renew_playbook_result is defined and event.renew_playbook_result.rc == 0
      actions:
        - debug:
            msg: "TLS Cert Renewal succeeded!"

    - name: Renew playbook failure
      condition: event.renew_playbook_result is defined and event.renew_playbook_result.rc != 0
      actions:
        - debug:
            msg: "TLS Cert renewal failed!"
